import { describe, it, expect } from "vitest";
import { generateMultiPageZplWithMap, type EmitSpan } from "./zplGenerator";
import { importZplText } from "./zplImportService";
import type { LabelConfig } from "../types/LabelConfig";
import type { LabelObject, Page } from "../types/Group";

const label: LabelConfig = { widthMm: 70, heightMm: 40, dpmm: 8 };

const text = (id: string, content: string, over: Partial<LabelObject> = {}): LabelObject =>
  ({
    id, type: "text", x: 10, y: 10, rotation: 0,
    props: { content, fontHeight: 30, fontWidth: 0, rotation: "N" },
    ...over,
  }) as never;

const expectWellFormed = (out: { text: string; spans: EmitSpan[] }) => {
  let cursor = -1;
  for (const s of out.spans) {
    expect(s.start).toBeGreaterThan(cursor);
    expect(s.end).toBeGreaterThan(s.start);
    expect(s.end).toBeLessThanOrEqual(out.text.length);
    cursor = s.end;
  }
};

const sliceOf = (out: { text: string; spans: EmitSpan[] }, objectId: string): string => {
  const s = out.spans.find((sp) => sp.objectId === objectId);
  expect(s).toBeDefined();
  return out.text.slice(s?.start, s?.end);
};

describe("generateMultiPageZplWithMap on model pages", () => {
  const pages: Page[] = [
    {
      objects: [
        text("a", "Alpha"),
        {
          id: "g", type: "group", x: 0, y: 0, rotation: 0,
          children: [text("b", "Beta", { y: 60 } as never)],
        } as never,
        text("hidden", "Ghost", { includeInExport: false } as never),
      ],
    },
  ];

  it("returns the exact export text with one span per emitted leaf", () => {
    const out = generateMultiPageZplWithMap(label, pages);
    expectWellFormed(out);
    expect(out.spans.map((s) => s.objectId)).toEqual(["a", "b"]);
    expect(sliceOf(out, "a")).toMatch(/^\^F[OT].*\^FDAlpha\^FS$/s);
    expect(sliceOf(out, "b")).toMatch(/^\^F[OT].*\^FDBeta\^FS$/s);
  });

  it("covers the ^FX comment of a commented leaf", () => {
    const commented: Page[] = [{ objects: [text("c", "Gamma", { comment: "note" } as never)] }];
    const out = generateMultiPageZplWithMap(label, commented);
    expect(sliceOf(out, "c")).toMatch(/^\^FXnote\n.*\^FDGamma\^FS$/s);
  });

  it("survives the cross-page ^JM reset splice", () => {
    const multi: Page[] = [
      { jmDensity: "B", objects: [text("p1", "One")] },
      { objects: [text("p2", "Two")] },
    ];
    const out = generateMultiPageZplWithMap(label, multi);
    expect(out.text).toContain("^JMA");
    expect(sliceOf(out, "p2")).toMatch(/^\^F[OT].*\^FDTwo\^FS$/s);
    expect(out.spans.find((s) => s.objectId === "p2")?.pageIndex).toBe(1);
  });
});

describe("generateMultiPageZplWithMap robustness", () => {
  it("holds its invariants across a 200-page document", () => {
    const many: Page[] = Array.from({ length: 200 }, (_, i) => ({
      jmDensity: i % 2 === 0 ? undefined : ("B" as const),
      objects: [text(`o${i}`, `P${i}`)],
    }));
    const out = generateMultiPageZplWithMap(label, many);
    expectWellFormed(out);
    expect(out.spans).toHaveLength(200);
    expect(out.spans[199]?.pageIndex).toBe(199);
    expect(sliceOf(out, "o137")).toMatch(/\^FDP137\^FS$/);
  });

  it("never throws on degenerate models", () => {
    expect(generateMultiPageZplWithMap(label, []).spans).toEqual([]);
    expect(generateMultiPageZplWithMap(label, [{ objects: [] }]).spans).toEqual([]);
    const excludedOnly: Page[] = [
      { objects: [text("x", "X", { includeInExport: false } as never)] },
    ];
    expect(generateMultiPageZplWithMap(label, excludedOnly).spans).toEqual([]);
  });
});

describe("generateMultiPageZplWithMap on overlay pages", () => {
  const fresh = () => text("new", "Fresh", { y: 200 } as never);
  const source = [
    "^XA",
    "^PW560",
    "^FO10,10^A0N,30,30^FDHello^FS",
    "^FO10,60^A0N,30,30^FDWorld^FS",
    "^XZ",
  ].join("\n");

  const importPages = (): Page[] => {
    const r = importZplText(source, label.dpmm);
    expect(r.pages[0]?.overlay).toBeDefined();
    return r.pages;
  };

  it("maps verbatim segments onto their original bytes", () => {
    const pages = importPages();
    const out = generateMultiPageZplWithMap(label, pages);
    expect(out.text).toBe(source);
    expectWellFormed(out);
    const ids = pages[0]?.objects.map((o) => o.id) ?? [];
    expect(sliceOf(out, ids[0] ?? "")).toBe("^FO10,10^A0N,30,30^FDHello^FS");
    expect(sliceOf(out, ids[1] ?? "")).toBe("^FO10,60^A0N,30,30^FDWorld^FS");
  });

  it("maps a dirty object onto its regenerated bytes, neighbours stay verbatim", () => {
    const pages = importPages();
    const [first, second] = pages[0]?.objects ?? [];
    if (!first || !second || first.type !== "text") throw new Error("fixture");
    const edited: Page[] = [
      {
        ...pages[0],
        objects: [
          { ...first, dirty: true, props: { ...first.props, content: "Edited" } },
          second,
        ],
      } as Page,
    ];
    const out = generateMultiPageZplWithMap(label, edited);
    expect(sliceOf(out, first.id)).toMatch(/\^FDEdited\^FS$/);
    expect(sliceOf(out, second.id)).toBe("^FO10,60^A0N,30,30^FDWorld^FS");
    expectWellFormed(out);
  });

  it("maps an appended object into the block before ^XZ", () => {
    const pages = importPages();
    const edited: Page[] = [
      { ...pages[0], objects: [...(pages[0]?.objects ?? []), text("new", "Fresh", { y: 120 } as never)] } as Page,
    ];
    const out = generateMultiPageZplWithMap(label, edited);
    expect(sliceOf(out, "new")).toMatch(/^\^F[OT].*\^FDFresh\^FS$/s);
    const span = out.spans.find((s) => s.objectId === "new");
    expect(span && span.end <= out.text.lastIndexOf("^XZ")).toBe(true);
    expectWellFormed(out);
  });

  it("keeps a CRLF stream byte-identical with spans on the original bytes", () => {
    const crlf = "^XA\r\n^PW560\r\n^FO10,10^A0N,30,30^FDHello^FS\r\n^XZ";
    const r = importZplText(crlf, label.dpmm);
    const out = generateMultiPageZplWithMap(label, r.pages);
    expect(out.text).toBe(crlf);
    const id = r.pages[0]?.objects[0]?.id ?? "";
    expect(sliceOf(out, id)).toBe("^FO10,10^A0N,30,30^FDHello^FS");
  });

  it("survives a ^CC-remapped prefix stream", () => {
    const remapped = "^CC/\n/FO10,10/A0N,30,30/FDHello/FS\n/XZ";
    const r = importZplText(`^XA\n${remapped}`, label.dpmm);
    const out = generateMultiPageZplWithMap(label, r.pages);
    expect(out.text).toBe(`^XA\n${remapped}`);
    expectWellFormed(out);
  });

  it("grows a span around an in-field ^JM splice instead of truncating it", () => {
    const src = "^XA\n^FO10,10^JM^A0N,30,30^FDhello^FS\n^XZ";
    const r = importZplText(src, label.dpmm);
    const pages: Page[] = [{ ...r.pages[0], jmDensity: "B" } as Page];
    const out = generateMultiPageZplWithMap(label, pages);
    const id = pages[0]?.objects[0]?.id ?? "";
    expect(sliceOf(out, id)).toBe("^FO10,10^JMB^A0N,30,30^FDhello^FS");
  });

  it("grows a span around an in-field ^JM injection across a line break", () => {
    // Unreadable ^JMBX: the injected ^JMA (delta +4) must not truncate the span.
    const src = "^XA\n^FO10,60^JMBX^A0N,30,30^FDabcdef\n^FS\n^XZ";
    const r = importZplText(src, label.dpmm);
    const out = generateMultiPageZplWithMap(label, r.pages);
    const id = r.pages[0]?.objects[0]?.id ?? "";
    expect(sliceOf(out, id)).toMatch(/\^FS$/);
  });

  it("keeps a CRLF page free of bare \\n after appending an object", () => {
    const crlf = "^XA\r\n^FO10,10^A0N,30,30^FDHello^FS\r\n^XZ";
    const r = importZplText(crlf, label.dpmm);
    const edited: Page[] = [
      { ...r.pages[0], objects: [...(r.pages[0]?.objects ?? []), text("new", "Fresh", { y: 120 } as never)] } as Page,
    ];
    const out = generateMultiPageZplWithMap(label, edited);
    expect(/(?<!\r)\n/.test(out.text)).toBe(false);
    expect(sliceOf(out, "new")).toMatch(/\^FDFresh\^FS$/);
    expectWellFormed(out);
  });

  it("keeps a CRLF page free of bare \\n after regenerating a dirty object", () => {
    const crlf =
      "^XA\r\n^FO10,10^A0N,30,30^FDHello^FS\r\n^FO10,60^A0N,30,30^FDWorld^FS\r\n^XZ";
    const r = importZplText(crlf, label.dpmm);
    const [first, ...rest] = r.pages[0]?.objects ?? [];
    if (!first || first.type !== "text") throw new Error("fixture");
    const edited: Page[] = [
      {
        ...r.pages[0],
        objects: [
          { ...first, dirty: true, props: { ...first.props, content: "Edited" } },
          ...rest,
        ],
      } as Page,
    ];
    const out = generateMultiPageZplWithMap(label, edited);
    expect(out.text).toContain("Edited");
    expect(/(?<!\r)\n/.test(out.text)).toBe(false);
  });

  it("terminates a verbatim field ^XZ closed before appending behind it", () => {
    // Without the ^FS the printer would drop "b" once "Fresh" follows it.
    const src = "^XA\n^FO10,10^A0N,30,30^FDa^FS\n^FO10,60^A0N,30,30^FDb\n^XZ";
    const page = importZplText(src, label.dpmm).pages[0];
    if (!page?.overlay) throw new Error("fixture");
    const out = generateMultiPageZplWithMap(label, [
      { ...page, objects: [...page.objects, fresh()] } as Page,
    ]);
    expectWellFormed(out);
    expect(out.text).toMatch(/\^FDb\n\^FS\n\^FO[^\n]*\^FDFresh\^FS\n\^XZ$/);
    expect(sliceOf(out, "new")).toMatch(/^\^FO.*\^FDFresh\^FS$/);
    expect(out.spans).toHaveLength(page.objects.length + 1);
  });

  it("keeps the overlay when a reverse-bg pair's field is ^XZ closed", () => {
    // The stash commits inside the closing flush; that token owns box and text.
    const src = "^XA\n^FO40,40^GB200,60,60^FS\n^FO40,40^A0N,40,40^FDx\n^XZ";
    const page = importZplText(src, label.dpmm).pages[0];
    expect(page?.overlay).toBeDefined();
    expect(generateMultiPageZplWithMap(label, [page as Page]).text).toBe(src);
  });

  it("links a stash ^XZ commits to its own bytes, not to the data-less tail field", () => {
    const src = "^XA\n^FO40,40^GB200,60,60^FS\n^FO40,200^A0N,40,40\n^XZ";
    const page = importZplText(src, label.dpmm).pages[0];
    if (!page?.overlay) throw new Error("fixture");
    const [box] = page.objects;
    if (!box) throw new Error("fixture");
    const out = generateMultiPageZplWithMap(label, [{ ...page, objects: [{ ...box, dirty: true, y: box.y + 10 }] } as Page]);
    expect(out.text.match(/\^GB/g)).toHaveLength(1);
    expect(out.text).toContain("^FO40,200^A0N,40,40");
  });

  it("regenerates when a removed field would let a dropped field's bytes print", () => {
    const src = "^XA\n^FO40,40^A0N,60,60^FDalpha\n^FO40,200^A0N,60,60^FDbeta^FS\n^XZ";
    const page = importZplText(src, label.dpmm).pages[0];
    if (!page?.overlay) throw new Error("fixture");
    expect(page.overlay.droppedField).toBe(true);
    expect(generateMultiPageZplWithMap(label, [page as Page]).text).toBe(src);
    const deleted = generateMultiPageZplWithMap(label, [{ ...page, objects: [] } as Page]);
    expect(deleted.text).not.toContain("alpha");
    const excluded = generateMultiPageZplWithMap(label, [
      { ...page, objects: page.objects.map((o) => ({ ...o, includeInExport: false })) } as Page,
    ]);
    expect(excluded.text).not.toContain("alpha");
  });

  it("reads the terminator case-insensitively before adding one", () => {
    const src = "^XA\n^FO10,10^A0N,30,30^FDa^fs\n^FO10,60^A0N,30,30^FDb\n^XZ";
    const page = importZplText(src, label.dpmm).pages[0];
    if (!page?.overlay) throw new Error("fixture");
    const [a] = page.objects;
    if (!a) throw new Error("fixture");
    const out = generateMultiPageZplWithMap(label, [{ ...page, objects: [a, fresh()] } as Page]);
    expect(out.text).not.toMatch(/\^fs\s*\^FS/i);
  });

  it("adds no second ^FS once the open tail was regenerated or deleted", () => {
    const src = "^XA\n^FO10,10^A0N,30,30^FDa^FS\n^FO10,60^A0N,30,30^FDb\n^XZ";
    const page = importZplText(src, label.dpmm).pages[0];
    if (!page?.overlay) throw new Error("fixture");
    const [a, b] = page.objects;
    if (!a || !b || b.type !== "text") throw new Error("fixture");
    const edited = generateMultiPageZplWithMap(label, [
      { ...page, objects: [a, { ...b, dirty: true, props: { ...b.props, content: "EDIT" } }, fresh()] } as Page,
    ]);
    expect(edited.text).not.toMatch(/\^FS\s*\^FS/);
    const deleted = generateMultiPageZplWithMap(label, [{ ...page, objects: [a, fresh()] } as Page]);
    expect(deleted.text).not.toMatch(/\^FS\s*\^FS/);
  });

  it("terminates a slot field ^XZ closed, which prints once a value is recalled", () => {
    // ZD230-measured: the recalled value prints where the ^FN sits.
    const src = "^XA\n^FO10,10^A0N,30,30^FDa^FS\n^FO10,60^A0N,30,30^FN1\n^XZ";
    const page = importZplText(src, label.dpmm).pages[0];
    if (!page?.overlay) throw new Error("fixture");
    const out = generateMultiPageZplWithMap(label, [
      { ...page, objects: [...page.objects, fresh()] } as Page,
    ]);
    expect(out.text).toMatch(/\^FN1\n\^FS\n\^FO[^\n]*\^FDFresh\^FS\n\^XZ$/);
  });

  it("terminates an unmodelled field ^XZ closed as well", () => {
    // No object span marks the ^IM field, so the guard must read the bytes.
    const src = "^XA\n^FO10,10^A0N,30,30^FDa^FS\n^FO10,60^IMR:LOGO.GRF\n^XZ";
    const page = importZplText(src, label.dpmm).pages[0];
    if (!page?.overlay) throw new Error("fixture");
    const out = generateMultiPageZplWithMap(label, [
      { ...page, objects: [...page.objects, fresh()] } as Page,
    ]);
    expect(out.text).toMatch(/\^IMR:LOGO\.GRF\n\^FS\n\^FO[^\n]*\^FDFresh\^FS\n\^XZ$/);
    // An overlay saved before the flag existed appends as it always did.
    const { openTail: _legacy, ...legacy } = page.overlay;
    const old = generateMultiPageZplWithMap(label, [
      { ...page, overlay: legacy, objects: [...page.objects, fresh()] } as Page,
    ]);
    expect(old.text).toMatch(/\^IMR:LOGO\.GRF\n\^FO[^\n]*\^FDFresh\^FS\n\^XZ$/);
  });

  const tornImport = () => {
    const src = "^XA\n^FO10,10^A0N,30,30^FDa^FS\n^XZ\n^FO10,60^A0N,30,30^FDb^XZ^FS";
    const r = importZplText(src, label.dpmm);
    const last = r.pages[r.pages.length - 1];
    if (!last?.overlay) throw new Error("fixture");
    const appended = (p: Page): Page => ({ ...p, objects: [...p.objects, fresh()] }) as Page;
    return { last, overlay: last.overlay, appended };
  };

  it("keeps every span when the last ^XZ sits right after the second object's bytes", () => {
    // The parser closes a field at ^XZ, so a fresh import has no torn span.
    const { last, appended } = tornImport();
    const clean = generateMultiPageZplWithMap(label, [appended(last)]);
    expectWellFormed(clean);
    expect(clean.spans).toHaveLength(last.objects.length + 1);
  });

  it("drops the span of an object the append splice tears apart", () => {
    // A design saved before this parser change can still carry the ^XZ inside
    // the object's segment. No contiguous span describes that object after the
    // splice, so the torn overlay is built here to cover it.
    const { last, overlay, appended } = tornImport();
    const segs = overlay.segments;
    const i = segs.findIndex((s) => s.kind === "object" && s.objectId === last.objects[1]?.id);
    const head = segs[i];
    if (!head) throw new Error("fixture");
    const torn = [...segs.slice(0, i), { ...head, text: segs.slice(i).map((s) => s.text).join("") }];
    const out = generateMultiPageZplWithMap(label, [appended({ ...last, overlay: { ...overlay, segments: torn, regenSafe: true } })]);
    expectWellFormed(out);
    expect(out.spans.some((s) => s.objectId === "new")).toBe(true);
    expect(out.spans).toHaveLength(last.objects.length);
  });

  it("emits no span for a deleted object and keeps the survivor anchored", () => {
    const pages = importPages();
    const [first, second] = pages[0]?.objects ?? [];
    if (!first || !second) throw new Error("fixture");
    const edited: Page[] = [{ ...pages[0], objects: [second] } as Page];
    const out = generateMultiPageZplWithMap(label, edited);
    expect(out.spans.map((s) => s.objectId)).toEqual([second.id]);
    expect(sliceOf(out, second.id)).toBe("^FO10,60^A0N,30,30^FDWorld^FS");
  });
});
